import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { IChildren } from "./types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Editor",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: IChildren) => (
  <html lang="en">
    <body className={inter.className}>{children}</body>
  </html>
);

export default RootLayout;
